"""empty message

Revision ID: 16444025d5f8
Revises: 98cd0c357744
Create Date: 2021-01-03 10:29:57.528040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16444025d5f8'
down_revision = '98cd0c357744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('id', sa.Integer()))
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER())
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('shows', 'id')
    # ### end Alembic commands ###
