"""empty message

Revision ID: 69012d5a3c58
Revises: f372d3376c2a
Create Date: 2020-12-31 18:39:15.926149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69012d5a3c58'
down_revision = 'f372d3376c2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###
