"""empty message

Revision ID: ba1fa050864b
Revises: d6f0c3722a93
Create Date: 2020-12-29 16:52:48.501101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1fa050864b'
down_revision = 'd6f0c3722a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
