--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)
-- Dumped by pg_dump version 12.5 (Ubuntu 12.5-0ubuntu0.20.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: actors; Type: TABLE; Schema: public; Owner: boram
--

CREATE TABLE public.actors (
    id integer NOT NULL,
    name character varying NOT NULL,
    age integer NOT NULL,
    gender character varying NOT NULL
);


ALTER TABLE public.actors OWNER TO boram;

--
-- Name: actors_id_seq; Type: SEQUENCE; Schema: public; Owner: boram
--

CREATE SEQUENCE public.actors_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.actors_id_seq OWNER TO boram;

--
-- Name: actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: boram
--

ALTER SEQUENCE public.actors_id_seq OWNED BY public.actors.id;


--
-- Name: movies; Type: TABLE; Schema: public; Owner: boram
--

CREATE TABLE public.movies (
    id integer NOT NULL,
    title character varying,
    release_date character varying NOT NULL
);


ALTER TABLE public.movies OWNER TO boram;

--
-- Name: movies_id_seq; Type: SEQUENCE; Schema: public; Owner: boram
--

CREATE SEQUENCE public.movies_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.movies_id_seq OWNER TO boram;

--
-- Name: movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: boram
--

ALTER SEQUENCE public.movies_id_seq OWNED BY public.movies.id;


--
-- Name: actors id; Type: DEFAULT; Schema: public; Owner: boram
--

ALTER TABLE ONLY public.actors ALTER COLUMN id SET DEFAULT nextval('public.actors_id_seq'::regclass);


--
-- Name: movies id; Type: DEFAULT; Schema: public; Owner: boram
--

ALTER TABLE ONLY public.movies ALTER COLUMN id SET DEFAULT nextval('public.movies_id_seq'::regclass);


--
-- Data for Name: actors; Type: TABLE DATA; Schema: public; Owner: boram
--

COPY public.actors (id, name, age, gender) FROM stdin;
1	Tom Cruise	58	Male
\.


--
-- Data for Name: movies; Type: TABLE DATA; Schema: public; Owner: boram
--

COPY public.movies (id, title, release_date) FROM stdin;
1	Mission Impossible	2019-03-04
\.


--
-- Name: actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: boram
--

SELECT pg_catalog.setval('public.actors_id_seq', 1, true);


--
-- Name: movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: boram
--

SELECT pg_catalog.setval('public.movies_id_seq', 1, true);


--
-- Name: actors actors_pkey; Type: CONSTRAINT; Schema: public; Owner: boram
--

ALTER TABLE ONLY public.actors
    ADD CONSTRAINT actors_pkey PRIMARY KEY (id);


--
-- Name: movies movies_pkey; Type: CONSTRAINT; Schema: public; Owner: boram
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_pkey PRIMARY KEY (id);


--
-- Name: movies movies_title_key; Type: CONSTRAINT; Schema: public; Owner: boram
--

ALTER TABLE ONLY public.movies
    ADD CONSTRAINT movies_title_key UNIQUE (title);


--
-- PostgreSQL database dump complete
--

